[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/terms"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/privacy"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "netlify/functions"
  external_node_modules = ["stripe", "@supabase/supabase-js", "jsr:@supabase/functions-js"]